### ISSUE TITLE
Create initial design for web

### ISSUE THREAD

**Issue by ut5tw** [3d-diploma-project/tetrahedron-web#5]
## Blocked by #6 
- [x] Create basic layout
- [x] Choose colors

**Comment by SachenkoTanya** [comment]
https://www.figma.com/design/qRI4mkLqebFSf43ICyF4mn/web?node-id=57-37&t=8BzU0pPYg7k6KLSE-4

**Comment by HappyMary16** [comment]
Hi @SachenkoTanya, could you please grant me access to the Figma project?

Please update the Confluence page with info about colors and other design information
https://getinfokhpi.atlassian.net/wiki/spaces/TE/pages/66060289/UX+Design

Also, please check the users stories in Jira assigned to you and move them to the corresponding status
https://getinfokhpi.atlassian.net/jira/software/projects/TET/boards/4/backlog
