### ISSUE TITLE
Preparation of the description of the initial design and technologies

### ISSUE THREAD

**Issue by ut5tw** [3d-diploma-project/tetrahedron-web#6]
- Prepare initial design
- Investigate technologies to use for designing

**Comment by SachenkoTanya** [comment]
[Technology.docx](https://github.com/user-attachments/files/17257754/Technology.docx)

**Comment by HappyMary16** [comment]
@SachenkoTanya  could you please add all info from your doc file to the Confluence page?
https://getinfokhpi.atlassian.net/wiki/spaces/TE/pages/66060289/UX+Design
