### ISSUE TITLE
Epic: web

### ISSUE THREAD

**Issue by ut5tw** [3d-diploma-project/tetrahedron-web#8]
### Figma design: [link](https://www.figma.com/design/qRI4mkLqebFSf43ICyF4mn/web?node-id=0-1&t=VITvYFzk62GLfe5b-1)

- #4

**Comment by HappyMary16** [comment]
Closed the epic as we are going to use Jira for task management

Also "web" is a terrible name/scope of an epic. Epic cannot be created for the development of a whole program. 
It must describe some part of the functionality, not everything.
